# See https://github.com/silverstripe-labs/silverstripe-travis-support for setup details

language: php 
php:
  - 5.4

sudo: false

addons:
  apt:
    packages:
    - poppler-utils

env:
  - DB=MYSQL CORE_RELEASE=3.1
  - DB=MYSQL CORE_RELEASE=3

before_script:
  - mkdir -p $HOME/bin
  - export PATH=$PATH:$HOME/bin
  - export SS_TIKA_ENDPOINT="http://localhost:9998/"
  - ./.travis/install_tika.sh
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script:
  - ($HOME/bin/tika-rest-server &) &> /dev/null
  - vendor/bin/phpunit --verbose textextraction/tests/
